'use client'
import { motion } from 'framer-motion'
import Link from 'next/link'
import React, { useState } from 'react'

type Props = {}

const Ad = ({
    title = 'Generated by Dreapic AI Art Generator',
}: {
    title?: string
}) => {
    return (
        <Link href="/">
            <motion.div
                className="mt-8 p-4 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-lg shadow-lg text-white relative overflow-hidden"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
            >
                <div className="relative z-10">
                    <h3 className="text-3xl font-bold mb-2">{title}</h3>
                    <p className="mb-4">
                        Create your own stunning AI-powered artwork now!
                    </p>
                    <div className="inline-block bg-white text-purple-600 font-semibold py-2 px-4 rounded hover:bg-purple-100 transition duration-300">
                        Make Your Art
                    </div>
                </div>
                <div className="absolute top-0 right-0 w-1/2 h-full overflow-hidden">
                    <img
                        src="/free/1.webp" // Replace with your image path
                        alt="AI Art Example"
                        className={`w-full h-full object-cover transition-opacity duration-1000 ease-in`}
                    />
                </div>
            </motion.div>
        </Link>
    )
}

export default Ad
